server:
  port: 8181
  max-http-request-header-size: 10KB
  servlet:
    context-path: /crde/gpsnel
  error:
    whitelabel:
      enabled: false  # disable the error page
    include-exception: true
    include-stacktrace: always
    path: /error   # /user-error

spring:
  application:
    name: Gestion du personnel de CRDE
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      location: /crde/gprsnupload
      max-file-size: 200MB	
  main:
    banner-mode: off
  #banner:
   # location:
  mvc:
    #static-path-pattern: "/resources/**"
    webjars-path-pattern: "/webjars/**"
  threads:
    virtual:
      enabled: true     # permet l'utilisation de threads virtuels dans toute l'application
  autoconfigure:
    exclude:
    -  org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  h2:
    console:
      enabled: true
      path : /admin/h2-console   # navigate to http://localhost:8181/crde/gpsnel/h2-console to see db UI
      settings.trace: false
      settings.web-allow-others: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:h2:~/crde/crdedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL #;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;        # jdbc:h2:~/olibilldb;AUTO_SERVER=TRUE
    #url: jdbc:h2:~/crde/crdedb;INIT=CREATE SCHEMA IF NOT EXISTS crde;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL #;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;        # jdbc:h2:~/olibilldb;AUTO_SERVER=TRUE
    #url: jdbc:h2:~/crde/crdedb;AUTO_SERVER=TRUE;MODE=LEGACY;
    #url: jdbc:h2:mem:crde/crdedb #;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE; MODE=MySQL
    ##url: jdbc:h2:~/crde/crdedb;AUTO_SERVER=TRUE;TRACE_LEVEL_FILE=3;TRACE_LEVEL_SYSTEM_OUT=3;IGNORE_UNKNOWN_SETTINGS=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    url: jdbc:h2:~/crde/crdedb;AUTO_SERVER=TRUE;IGNORE_UNKNOWN_SETTINGS=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: admin
    password: admin123
    driver-class-name: org.h2.Driver #org.postgresql.Driver #org.h2.Driver
    hikari:
      idle-timeout: 50000
  jpa:
    hibernate:
      ddl-auto: update #update #create-drop #update ##none --for flyway
     # naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #show-sql: true
    ##database-platform: org.hibernate.dialect.PostgreSQLDialect #org.hibernate.dialect.H2Dialect #org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true ##false --for flyway
    #globally_quoted_identifiers: true
    #generate-ddl: true   
  sql:
     init:
       #platform: h2
       mode: always #never #always
       schema-locations: classpath:db/sql/schema.sql
       data-locations: classpath:db/sql/data/status.sql, classpath:db/sql/data/lieuxaffectations.sql, classpath:db/sql/data/fonctions.sql, classpath:db/sql/data/typesemployes.sql, classpath:db/sql/data/employes.sql, classpath:db/sql/data/affectations.sql, classpath:db/sql/data/conges.sql, classpath:db/sql/data/missions.sql, classpath:db/sql/data/visites.sql, classpath:db/sql/data/utilisateurs.sql, classpath:db/sql/data/missionsemployes.sql, classpath:db/sql/data/autorisationssortie.sql 
       #dataLocations: classpath:db/sql/status.sql, classpath:db/sql/lieuxaffectations.sql, classpath:db/sql/fonctions.sql, classpath:db/sql/typesemployes.sql, classpath:db/sql/employes.sql, classpath:db/sql/affectations.sql, classpath:db/sql/conges.sql, classpath:db/sql/missions.sql, classpath:db/sql/visites.sql, classpath:db/sql/utilisateurs.sql, classpath:db/sql/missionsemployes.sql, classpath:db/sql/autorisationssortie.sql  #, classpath:data/affectations.sql, classpath:data/conges.sql, classpath:data/missions.sql, classpath:data/visites.sql
       continue-on-error: true  # if the scripts cause exceptions, the application does not fail to start
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  batch:
    jdbc:
      initialize-schema: never
  web:
    resources:
      cache:
        period: 120000
  #flyway:
   # enabled: true
   # locations: classpath:db/migrations
   # baseline-on-migrate: true
stockagecrde:
  emplacement: /dossier-crde-images