--CREATE SCHEMA IF NOT EXISTS;
CREATE TABLE IF NOT EXISTS affectation (id bigint GENERATED BY DEFAULT AS IDENTITY, 
reference_affect VARCHAR(50), 
emplacement_affect VARCHAR(50),
date_debut_affect TIMESTAMP(9) WITH TIME ZONE,
date_fin_affect TIMESTAMP(9) WITH TIME ZONE,
date_prise_service TIMESTAMP(9) WITH TIME ZONE,
info_supplementaires VARCHAR(60),
status_affect VARCHAR(15),
date_status_affect TIMESTAMP(9) WITH TIME ZONE,   
num_note_service VARCHAR(15),
employe_id long,
lieu_affectation_id long,
fonction_id long,
affect_creee_le TIMESTAMP(9) WITH TIME ZONE, affect_creee_par VARCHAR(15), 
affect_modifiee_le TIMESTAMP(9) WITH TIME ZONE, affect_modifiee_par VARCHAR(15),
constraint fk_affect_emp FOREIGN key (employe_id) references employe(id),
constraint fk_affect_lieu_affect FOREIGN key (lieu_affectation_id) references lieu_affectation(id),
constraint fk_affect_fonction FOREIGN key (fonction_id) references fonction(id)
);

insert into affectation (num_note_service, reference_affect, emplacement_affect, date_debut_affect, date_fin_affect, date_prise_service, info_supplementaires, status_affect, date_status_affect, employe_id, lieu_affectation_id, fonction_id) 
values ('15', 'Decret 1/2019', 'Présidence', '20190130', '20190130', '20190205', 'Décret présidentiel', 'Approuvée', '20190130', 1L, 1L, 1L);
insert into affectation (num_note_service, reference_affect, emplacement_affect, date_debut_affect, date_fin_affect, date_prise_service, info_supplementaires, status_affect, date_status_affect, employe_id, lieu_affectation_id, fonction_id) 
values ('21', 'Décision 06/2023', 'Aeroport de BG', '20230607', '20230607', '20230617', 'Note de service', 'Approuvée', '20230607', 2L, 3L, 4L);
insert into affectation (num_note_service, reference_affect, emplacement_affect, date_debut_affect, date_fin_affect, date_prise_service, info_supplementaires, status_affect, date_status_affect, employe_id, lieu_affectation_id, fonction_id) 
values ('26', 'Arrt 11/2022', 'Aeroport de BG', '20221115', '20221115', '20230105', 'Note de service', 'Approuvée', '20221115', 3L, 2L, 6L);