--CREATE SCHEMA IF NOT EXISTS;
CREATE TABLE IF NOT EXISTS mission (id bigint GENERATED BY DEFAULT AS IDENTITY,
nature_mission VARCHAR(50), 
cadre_mission VARCHAR(50),
date_depart TIMESTAMP(9) WITH TIME ZONE,
date_retour TIMESTAMP(9) WITH TIME ZONE, 
pays_mission VARCHAR(30), 
ville_mission VARCHAR(30),
motif_mission VARCHAR(30), 
info_supplementaires VARCHAR(80),
type_ordre_mission VARCHAR(25),
num_ordre_mission VARCHAR(15),  
status_mission VARCHAR(25),
date_status_mission TIMESTAMP(9) WITH TIME ZONE, 
employe_id long,
mission_creee_le TIMESTAMP(9) WITH TIME ZONE, mission_creee_par VARCHAR(15), 
mission_modifiee_le TIMESTAMP(9) WITH TIME ZONE, mission_modifiee_par VARCHAR(15),
constraint fk_miss_emp FOREIGN key (employe_id) references employe(id)
);
insert into mission (num_ordre_mission, type_ordre_mission, nature_mission, cadre_mission, date_depart, date_retour, pays_mission, ville_mission, motif_mission, status_mission, date_status_mission, employe_id) 
values ('12', 'ordre-mission', 'Seminaire échange', 'Échange international sur le développement', '20250828', '20250908', 'Afrique du Sud', 'Pretoria', 'Mission officielle', 'En attente de validation', '20250903', 3L);