CREATE TABLE IF NOT EXISTS fonction (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fonction_code VARCHAR(5) UNIQUE, fonction VARCHAR(50), fonction_cree_le TIMESTAMP(9) WITH TIME ZONE, fonction_cree_par VARCHAR(15), fonction_modifie_le TIMESTAMP(9) WITH TIME ZONE, fonction_modifie_par VARCHAR(15));
BEGIN TRY
	insert into fonction (FONCTION_CODE, FONCTION) 
	values ('MIN', 'Ministre');
	insert into fonction (FONCTION_CODE, FONCTION) 
	values ('SP', 'Secrétaire particulier');
	insert into fonction (FONCTION_CODE, FONCTION) 
	values ('ASS', 'Assistant');
	insert into fonction (FONCTION_CODE, FONCTION) 
	values ('DIR', 'Directeur');
	insert into fonction (FONCTION_CODE, FONCTION)
	values ('CSV', 'Chef de service');
	insert into fonction (FONCTION_CODE, FONCTION)
	values ('CSB', 'Chef de bureau');
	insert into fonction (FONCTION_CODE, FONCTION)
	values ('PERS', 'Personnel');
	insert into fonction (FONCTION_CODE, FONCTION)
	values ('ACAMP', 'Aide de camp');
	insert into fonction (FONCTION_CODE, FONCTION)
	values ('CHAUF', 'Chauffeur');
	insert into fonction (FONCTION_CODE, FONCTION)
	values ('AUT', 'Autre');
END TRY
BEGIN CATCH
    -- Capture and display the error.
    PRINT 'Constraint violation: ' + ERROR_MESSAGE();
END CATCH;