--CREATE SCHEMA IF NOT EXISTS;
--CREATE SCHEMA IF NOT EXISTS crde;
CREATE TABLE IF NOT EXISTS status (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
status_code VARCHAR(4), 
status VARCHAR(50), 
status_cree_le TIMESTAMP(9) WITH TIME ZONE, 
status_cree_par VARCHAR(15), 
status_modifie_le TIMESTAMP(9) WITH TIME ZONE, 
status_modifie_par VARCHAR(15),
UNIQUE(status_code));

CREATE TABLE IF NOT EXISTS type_employe (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
type_emp_code VARCHAR(4), 
type_emp VARCHAR(50), type_emp_cree_le TIMESTAMP(9) WITH TIME ZONE, type_emp_cree_par VARCHAR(15), 
type_emp_modifie_le TIMESTAMP(9) WITH TIME ZONE, type_emp_modifie_par VARCHAR(15),
constraint uniq_typeemp UNIQUE(type_emp_code));

CREATE TABLE IF NOT EXISTS type_mission (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
type_miss_code VARCHAR(4), type_miss VARCHAR(50), type_miss_cree_le TIMESTAMP(9) WITH TIME ZONE, 
type_miss_cree_par VARCHAR(15), type_miss_modifie_le TIMESTAMP(9) WITH TIME ZONE, 
type_miss_modifie_par VARCHAR(15),
constraint uniq_typemiss UNIQUE(type_miss_code));

CREATE TABLE IF NOT EXISTS lieu_affectation (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
lieu_affect_code VARCHAR(4), 
lieu_affect VARCHAR(50), lieu_affect_cree_le TIMESTAMP(9) WITH TIME ZONE, 
lieu_affect_cree_par VARCHAR(15), lieu_affect_modifie_le TIMESTAMP(9) WITH TIME ZONE, 
lieu_affect_modifie_par VARCHAR(15),
constraint uniq_lieuaffect UNIQUE(lieu_affect_code));

CREATE TABLE IF NOT EXISTS fonction (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
fonction_code VARCHAR(5), 
fonction VARCHAR(50), fonction_cree_le TIMESTAMP(9) WITH TIME ZONE, 
fonction_cree_par VARCHAR(15), fonction_modifie_le TIMESTAMP(9) WITH TIME ZONE, 
fonction_modifie_par VARCHAR(15),
constraint uniq_fonction UNIQUE(fonction_code));

CREATE TABLE IF NOT EXISTS employe (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
emp_matricule VARCHAR(15), 
emp_nom VARCHAR(30),
emp_pren VARCHAR(30),
emp_civilite VARCHAR(20),
emp_urlphoto VARCHAR(100),
emp_urlsignature VARCHAR(100),
emp_telephone VARCHAR(15),
emp_email VARCHAR(30),
type_employe_id long,
emp_status_id long,
emp_lieu_affectation_id long,
emp_fonction_id long,
reference_decret_entree VARCHAR(20),
date_decret_entree TIMESTAMP(9) WITH TIME ZONE,
reference_decret_sortie VARCHAR(20),
date_decret_sortie TIMESTAMP(9) WITH TIME ZONE,
emp_cree_le TIMESTAMP(9) WITH TIME ZONE, 
emp_cree_par VARCHAR(15), 
emp_modifie_le TIMESTAMP(9) WITH TIME ZONE, 
emp_modifie_par VARCHAR(15),
constraint uniq_matricule UNIQUE(emp_matricule),
constraint fk_emp_type_emp FOREIGN key (type_employe_id) references type_employe(id),
constraint fk_emp_status FOREIGN key (emp_status_id) references status(id),
constraint fk_emp_lieu_affect FOREIGN key (emp_lieu_affectation_id) references lieu_affectation(id),
constraint fk_emp_fonction FOREIGN key (emp_fonction_id) references fonction(id)
);

CREATE TABLE IF NOT EXISTS affectation (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
reference_affect VARCHAR(50), 
categorie_affect VARCHAR(30),
ville_residence VARCHAR(50),
pays_residence VARCHAR(50),
emplacement_affect VARCHAR(50),
date_debut_affect TIMESTAMP(9) WITH TIME ZONE,
date_fin_affect TIMESTAMP(9) WITH TIME ZONE,
date_prise_service TIMESTAMP(9) WITH TIME ZONE,
info_supplementaires VARCHAR(60),
status_affect VARCHAR(15),
date_status_affect TIMESTAMP(9) WITH TIME ZONE,   
num_note_service VARCHAR(15),
employe_id long,
lieu_affectation_id long,
fonction_id long,
affect_creee_le TIMESTAMP(9) WITH TIME ZONE, affect_creee_par VARCHAR(15), 
affect_modifiee_le TIMESTAMP(9) WITH TIME ZONE, affect_modifiee_par VARCHAR(15),
constraint fk_affect_emp FOREIGN key (employe_id) references employe(id),
constraint fk_affect_lieu_affect FOREIGN key (lieu_affectation_id) references lieu_affectation(id),
constraint fk_affect_fonction FOREIGN key (fonction_id) references fonction(id)
);

CREATE TABLE IF NOT EXISTS conge (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
date_debut_conge TIMESTAMP(9) WITH TIME ZONE,
date_fin_conge TIMESTAMP(9) WITH TIME ZONE,
info_supplementaires VARCHAR(100), 
status_conge VARCHAR(15),
date_status_conge TIMESTAMP(9) WITH TIME ZONE, 
num_note_service_conge VARCHAR(12),
type_demande_conge VARCHAR(30),
employe_id long,
employe_remplacant_id long,
conge_cree_le TIMESTAMP(9) WITH TIME ZONE, conge_cree_par VARCHAR(15), 
conge_modifie_le TIMESTAMP(9) WITH TIME ZONE, conge_modifie_par VARCHAR(15),
constraint fk_conge_emp FOREIGN key (employe_id) references employe(id),
constraint fk_conge_emp_rempl FOREIGN key (employe_remplacant_id) references employe(id)
);

CREATE TABLE IF NOT EXISTS autorisation_sortie (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
as_date_depart TIMESTAMP(9) WITH TIME ZONE,
as_date_retour TIMESTAMP(9) WITH TIME ZONE,
as_ville VARCHAR(30), 
as_pays VARCHAR(40), 
as_num VARCHAR(12),
motif_sortie VARCHAR(100),
status_as VARCHAR(15),
date_status_as TIMESTAMP(9) WITH TIME ZONE, 
conge_id long,
as_cree_le TIMESTAMP(9) WITH TIME ZONE, as_cree_par VARCHAR(15), 
as_modifie_le TIMESTAMP(9) WITH TIME ZONE, as_modifie_par VARCHAR(15),
constraint fk_as_conge FOREIGN key (conge_id) references conge(id)
);

CREATE TABLE IF NOT EXISTS mission (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nature_mission VARCHAR(50), 
cadre_mission VARCHAR(50),
date_depart TIMESTAMP(9) WITH TIME ZONE,
date_retour TIMESTAMP(9) WITH TIME ZONE,
duree_en_let_mission VARCHAR(50), 
pays_mission VARCHAR(30), 
ville_mission VARCHAR(30),
motif_mission VARCHAR(30), 
info_supplementaires VARCHAR(100),
type_ordre_mission VARCHAR(25),
num_ordre_mission VARCHAR(15),  
status_mission VARCHAR(25),
date_status_mission TIMESTAMP(9) WITH TIME ZONE, 
employe_id long,
mission_creee_le TIMESTAMP(9) WITH TIME ZONE, mission_creee_par VARCHAR(15), 
mission_modifiee_le TIMESTAMP(9) WITH TIME ZONE, mission_modifiee_par VARCHAR(15)--,
--constraint fk_miss_emp FOREIGN key (employe_id) references employe(id)
);

CREATE TABLE IF NOT EXISTS mission_employe (employe_id bigint, 
mission_id bigint,
is_employe_chef_mission boolean,
miss_emp_creee_le TIMESTAMP(9) WITH TIME ZONE, miss_emp_creee_par VARCHAR(15), 
miss_emp_modifiee_le TIMESTAMP(9) WITH TIME ZONE, miss_emp_modifiee_par VARCHAR(15),
constraint pk_miss_emp_key primary key(employe_id, mission_id),
constraint fk_miss_emp_empkey FOREIGN key (employe_id) references employe(id),
constraint fk_miss_emp_misskey FOREIGN key (mission_id) references mission(id)
);

CREATE TABLE IF NOT EXISTS utilisateur (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, utilisateur_firstname VARCHAR(30), utilisateur_lastname VARCHAR(30), utilisateur_email VARCHAR(50), utilisateur_phone_number VARCHAR(15), utilisateur_nom_connexion VARCHAR(15), utilisateur_mot_de_passe VARCHAR(12), utilisateur_role VARCHAR(5), utilisateur_status VARCHAR(15), utilisateur_cree_le TIMESTAMP(9) WITH TIME ZONE, utilisateur_cree_par VARCHAR(15), utilisateur_modifie_le TIMESTAMP(9) WITH TIME ZONE, utilisateur_modifie_par VARCHAR(15));
CREATE TABLE IF NOT EXISTS visite (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
civilite_visiteur VARCHAR(30), 
nom_visiteur VARCHAR(30),
prenom_visiteur VARCHAR(30),
fonction_visiteur VARCHAR(30),
pays_visiteur VARCHAR(30),
date_debut_visite TIMESTAMP(9) WITH TIME ZONE,
date_fin_visite TIMESTAMP(9) WITH TIME ZONE,
duree_visite INT,
--date_prise_service TIMESTAMP(9) WITH TIME ZONE,
but_visite VARCHAR(100),
employe_id long,
status_visite VARCHAR(15),
date_status_visite TIMESTAMP(9) WITH TIME ZONE,
--visite_est_acceptee boolean, visite_est_acceptee_le TIMESTAMP(9) WITH TIME ZONE,  
visite_creee_le TIMESTAMP(9) WITH TIME ZONE, visite_creee_par VARCHAR(15), 
visite_modifiee_le TIMESTAMP(9) WITH TIME ZONE, visite_modifiee_par VARCHAR(15),
constraint fk_visite_emp FOREIGN key (employe_id) references employe(id)
);