--CREATE SCHEMA IF NOT EXISTS;
--CREATE SCHEMA IF NOT EXISTS crde;
CREATE TABLE IF NOT EXISTS status (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, status_code VARCHAR(4) UNIQUE, status VARCHAR(50), status_cree_le TIMESTAMP(9) WITH TIME ZONE, status_cree_par VARCHAR(15), status_modifie_le TIMESTAMP(9) WITH TIME ZONE, status_modifie_par VARCHAR(15));
--CREATE TABLE IF NOT EXISTS member (id SERIAL PRIMARY KEY, member_first_name VARCHAR(30), member_last_name VARCHAR(30), member_email VARCHAR(50), member_phone_number VARCHAR(20), member_username VARCHAR(20) UNIQUE, member_password VARCHAR(150), member_role VARCHAR(15), member_status VARCHAR(15), member_created TIMESTAMP(9) WITH TIME ZONE, member_created_by VARCHAR(15), member_last_updated TIMESTAMP(9) WITH TIME ZONE, member_last_updated_by VARCHAR(15));
BEGIN TRY
	insert into status (STATUS_CODE, STATUS) 
	values ('SVCE', 'En service');
	insert into status (STATUS_CODE, STATUS)
	values ('CGE', 'En congé');
	insert into status (STATUS_CODE, STATUS)
	values ('MSN', 'En mission');
	insert into status (STATUS_CODE, STATUS)
	values ('STG', 'Stagiaire');
	insert into status (STATUS_CODE, STATUS)
	values ('NACT', 'Non actif');
	insert into status (STATUS_CODE, STATUS)
	values ('AUT', 'Autre');
END TRY
BEGIN CATCH
	PRINT 'Constraint violation: ' + ERROR_MESSAGE();
END CATCH;
--values (1L, 'SVCE', 'En service');
--insert into status (ID, STATUS_CODE, STATUS)
--values (2L, 'CGE', 'En congé');
--insert into status (ID, STATUS_CODE, STATUS)
--values (3L, 'MSN', 'En mission');
--insert into status (ID, STATUS_CODE, STATUS)
--values (4L, 'STG', 'Stagiaire');
--insert into status (ID, STATUS_CODE, STATUS)
--values (5L, 'NACT', 'Non actif');
--insert into status (ID, STATUS_CODE, STATUS)
--values (6L, 'AUT', 'Autre');*/