CREATE TABLE IF NOT EXISTS type_employe (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type_emp_code VARCHAR(4) UNIQUE, type_emp VARCHAR(50), type_emp_cree_le TIMESTAMP(9) WITH TIME ZONE, type_emp_cree_par VARCHAR(15), type_emp_modifie_le TIMESTAMP(9) WITH TIME ZONE, type_emp_modifie_par VARCHAR(15));
BEGIN TRY
	insert into type_employe (TYPE_EMP_CODE, TYPE_EMP) 
	values ('CIV', 'Civile');
	insert into type_employe (TYPE_EMP_CODE, TYPE_EMP) 
	values ('POL', 'Policier');
	insert into type_employe (TYPE_EMP_CODE, TYPE_EMP) 
	values ('GEN', 'Gendarme');
	insert into type_employe (TYPE_EMP_CODE, TYPE_EMP)
	values ('MIL', 'Militaire');
	insert into type_employe (TYPE_EMP_CODE, TYPE_EMP) 
	values ('AUT', 'Autre');
END TRY
BEGIN CATCH
    -- Capture and display the error.
    PRINT 'Constraint violation: ' + ERROR_MESSAGE();
END CATCH;