CREATE TABLE IF NOT EXISTS type_mission (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type_miss_code VARCHAR(4) UNIQUE, type_miss VARCHAR(50), type_miss_cree_le TIMESTAMP(9) WITH TIME ZONE, type_miss_cree_par VARCHAR(15), type_miss_modifie_le TIMESTAMP(9) WITH TIME ZONE, type_miss_modifie_par VARCHAR(15));
BEGIN TRY
	insert into type_mission (TYPE_MISS_CODE, TYPE_MISS) 
	values ('MISS', 'Mission');
	insert into type_mission (TYPE_MISS_CODE, TYPE_MISS) 
	values ('MIGP', 'Mission de groupe');
	insert into type_employe (TYPE_MISS_CODE, TYPE_MISS) 
	values ('AUT', 'Autre');
END TRY
BEGIN CATCH
    -- Capture and display the error.
    PRINT 'Constraint violation: ' + ERROR_MESSAGE();
END CATCH;