--CREATE SCHEMA IF NOT EXISTS;
CREATE TABLE IF NOT EXISTS visite (id bigint GENERATED BY DEFAULT AS IDENTITY, 
civilite_visiteur VARCHAR(30), 
nom_visiteur VARCHAR(30),
prenom_visiteur VARCHAR(30),
fonction_visiteur VARCHAR(30),
pays_visiteur VARCHAR(30),
date_debut_visite TIMESTAMP(9) WITH TIME ZONE,
date_fin_visite TIMESTAMP(9) WITH TIME ZONE,
duree_visite INT,
--date_prise_service TIMESTAMP(9) WITH TIME ZONE,
but_visite VARCHAR(60),
employe_id long,
status_visite VARCHAR(15),
date_status_visite TIMESTAMP(9) WITH TIME ZONE,
--visite_est_acceptee boolean, visite_est_acceptee_le TIMESTAMP(9) WITH TIME ZONE,  
visite_creee_le TIMESTAMP(9) WITH TIME ZONE, visite_creee_par VARCHAR(15), 
visite_modifiee_le TIMESTAMP(9) WITH TIME ZONE, visite_modifiee_par VARCHAR(15),
constraint fk_visite_emp FOREIGN key (employe_id) references employe(id)
);
insert into visite (date_debut_visite, date_fin_visite, duree_visite, civilite_visiteur, but_visite, nom_visiteur, prenom_visiteur, fonction_visiteur, pays_visiteur, employe_id, visite_creee_le, visite_creee_par, status_visite, date_status_visite) 
values ('20250913', '20250928', '15', 'Mr', 'Renforcement de coopérations', 'Coq', 'Martinez', 'Envoyé spécial', 'France', 1L, '20250904', 'admin', 'Approuvé', '20250910');